Controllers/CarController.cs
using EvoWebsite.Data;
using EvoWebsite.Models;
using EvoWebsite.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace EvoWebsite.Controllers
{
    public class CarController : Controller
    {
        private readonly CarDbContext db;

        public CarController(CarDbContext context)
        {
            db = context;
        }

        [Route("[controller]")]
        [Route("[controller]/index")]
        [Route("[controller]/index/{*search}")]
        [Route("[controller]/index/{search?}")]
        public IActionResult Index(string search)
        {
            
            List<Car> cars = db.Cars.ToList();
            List<Car> searchCars = new List<Car>();
            if (search != null)
            {
                foreach(Car c in cars)
                {
                    var input = c.Name;
                    var output1 = Regex.Replace(input.Split()[0], @"[^0-9a-zA-Z\ ]+", "");

                    if (c.Name.ToLower().Trim() == search.ToLower().Trim())
                    {
                        searchCars.Add(c);
                    }else if(output1.Trim().ToLower() == search.ToLower().Trim())
                    {
                        searchCars.Add(c);
                    }

                }

                    CarListVM model2 = new CarListVM() { cars = searchCars };
                    return View(model2);

            }
            CarListVM model = new CarListVM() { cars = cars };
            return View(model);
        }

        public IActionResult Supers()
        {
            List<Car> supers = db.Cars.Where(e => e.Type == "Super").ToList();
            CarListVM model = new CarListVM() { cars = supers };
            return View(model);
        }

        public IActionResult Sports()
        {
            List<Car> sports = db.Cars.Where(e => e.Type == "Sport").ToList();
            CarListVM model = new CarListVM() { cars = sports };
            return View(model);
        }

        public IActionResult SportsClassics()
        {
            List<Car> sportclassics = db.Cars.Where(e => e.Type == "SportClassics").ToList();
            CarListVM model = new CarListVM() { cars = sportclassics };
            return View(model);
        }

        public IActionResult Sedans()
        {
            List<Car> sedans = db.Cars.Where(e => e.Type == "Sedans").ToList();
            CarListVM model = new CarListVM() { cars = sedans };
            return View(model);
        }

        public IActionResult SUVs()
        {
            List<Car> suvs = db.Cars.Where(e => e.Type == "SUV").ToList();
            CarListVM model = new CarListVM() { cars = suvs };
            return View(model);
        }

        public IActionResult Muscles()
        {
            List<Car> muscles = db.Cars.Where(e => e.Type == "Muscle").ToList();
            CarListVM model = new CarListVM() { cars = muscles };
            return View(model);
        }

        public IActionResult Coupes()
        {
            List<Car> coupes = db.Cars.Where(e => e.Type == "Coupe").ToList();
            CarListVM model = new CarListVM() { cars = coupes };
            return View(model);
        }

        public IActionResult Compacts()
        {
            List<Car> compacts = db.Cars.Where(e => e.Type == "Compact").ToList();
            CarListVM model = new CarListVM() { cars = compacts };
            return View(model);
        }

        public IActionResult Vans()
        {
            List<Car> vans = db.Cars.Where(e => e.Type == "Van").ToList();
            CarListVM model = new CarListVM() { cars = vans };
            return View(model);
        }

        public IActionResult Offroad()
        {
            List<Car> offroads = db.Cars.Where(e => e.Type == "Offroad").ToList();
            CarListVM model = new CarListVM() { cars = offroads };
            return View(model);
        }
        public IActionResult Motos()
        {
            List<Car> motos = db.Cars.Where(e => e.Type == "Moto").ToList();
            CarListVM model = new CarListVM() { cars = motos };
            return View(model);
        }
    }
}

Controllers/OrderController.cs
using EvoWebsite.Data;
using EvoWebsite.Models;
using EvoWebsite.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoWebsite.Controllers
{
    public class OrderController : Controller
    {
        private readonly CarDbContext db;

        public OrderController(CarDbContext context)
        {
            db = context;
        }

        [Route("[controller]")]
        [Route("[controller]/index")]

        public IActionResult Index()
        {
            List<Order> orders = db.Orders.ToList();
            OrderListVM model = new OrderListVM() { Orders = orders };
            return View(model);
        }

        [Route("commande")]
        [Route("commande/{*voiture}")]
        [Route("commande/{voiture?}")]
        public IActionResult Order(string voiture)
        {
            if(voiture != null)
            {
                CreateOrderVM model = new CreateOrderVM()
                {
                    CarName = voiture,
                    ClientName = "",
                    Telephone = ""
                };
                return View(model);
            }

            return View();
        }

        public IActionResult CreateOrder(CreateOrderVM order)
        {
            Order orderDb = new Order() { OrderId = 0, Date = DateTime.Now, ClientName = order.ClientName, CarName = order.CarName, Telephone = order.Telephone };
            db.Orders.Add(orderDb);
            db.SaveChanges();

            CarListVM model = new CarListVM() { cars = db.Cars.ToList() };
            return View("/Views/Car/Index.cshtml", model);
        }

        [Route("commande/supprime/{*id}")]
        [Route("commande/supprime/{id?}")]
        public IActionResult RemoveOrder(int id) 
        {
            List<Order> orders = db.Orders.ToList();
            foreach(Order o in orders)
            {
                if(o.OrderId == id)
                {
                    db.Orders.Remove(o);
                }
            }
            db.SaveChanges();

            List<Order> orders2 = db.Orders.ToList();
            OrderListVM model = new OrderListVM() { Orders = orders2 };
            return View("Index", model);
        }

        [Route("commande/modif/{*id}")]
        [Route("commande/modif/{id?}")]
        public IActionResult EditOrder(int id)
        {
            List<Order> orders = db.Orders.ToList();
            EditOrderVM model = new EditOrderVM();
            foreach (Order o in orders)
            {
                if (o.OrderId == id)
                {
                    model = new EditOrderVM() { CarName = o.CarName, ClientName = o.ClientName, Telephone = o.Telephone, OrderId = id };
                }
            }


            return View("Edit",model);
        }

        public IActionResult EditOrderFinal(EditOrderVM order)
        {
            List<Order> orders = db.Orders.ToList();
            Order newOrder = new Order() { OrderId = order.OrderId, CarName = order.CarName, ClientName = order.ClientName, Telephone = order.Telephone};
            foreach(Order o in orders)
            {
                if(o.OrderId == order.OrderId)
                {
                    db.Entry(o).CurrentValues.SetValues(newOrder);
                }
            }
            db.SaveChanges();

            List<Order> orders2 = db.Orders.ToList();
            OrderListVM model = new OrderListVM() { Orders = orders2 };
            return View("Index", model);
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EvoWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cabin:700">
    <link rel="stylesheet" href="/fonts/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/site.css?version=15" />
</head>

<body>
    <div class="container fixed-top">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark rounded">
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">
                <img class="rounded" src="/img/logoEvo2.png" height="40px">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                </div>
                <div class="navbar-nav ml-auto">
                    <a class="nav-link nav-item rounded nav-button" asp-area="" asp-controller="Home" asp-action="Index">ACCEUIL</a>
                    <a class="nav-link nav-item rounded nav-button" asp-area="" asp-controller="Car" asp-action="Index">CATALOGUE</a>
                    <a class="nav-link nav-item rounded nav-button" asp-area="" asp-controller="Order" asp-action="Order">COMMANDES</a>
                    <a class="nav-link nav-item rounded nav-button" asp-area="" asp-controller="Order" asp-action="Index">LISTES</a>
                </div>
            </div>
        </nav>
    </div>
        <!--<nav class="navbar navbar-light navbar-expand-md navbar navbar-expand-lg w-50 m-auto fixed-top" id="mainNav" style="background-color: #36393F; border-radius: 0px 0px 20px 20px;">
            <div class="container">
                <img class="rounded shadow" src="/img/logo.png">

               
                <div class="navbar-collapse collapse" id="navbarResponsive">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item nav-link js-scroll-trigger">
                            <a class="nav-link js-scroll-trigger rounded" style="background: #3b1a53;margin: 0px;padding: 15px;" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item nav-link js-scroll-trigger">
                            <a class="nav-link js-scroll-trigger rounded" style="background: #3b1a53;margin: 0px;padding: 15px;" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>-->
    
    
            
                @RenderBody()
        
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>