Controllers/CarlistController.cs
using EvoWebsite.Data;
using EvoWebsite.Models;
using EvoWebsite.ViewsModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvoWebsite.Controllers
{
    public class CarlistController : Controller
    {
        private readonly CarDbContext db;

        public CarlistController(CarDbContext context)
        {
            db = context;
        }

        [Route("[controller]")]
        [Route("[controller]/index")]

        public IActionResult Index()
        {
            List<Car> cars = db.Cars.ToList();
            CarListVM model = new CarListVM() { cars = cars };
            return View(model);
        }

        

        [Route("voiture/supprime/{*id}")]
        [Route("voiture/supprime/{id?}")]
        public IActionResult RemoveCar(int id) 
        {
            List<Car> cars = db.Cars.ToList();
            foreach(Car c in cars)
            {
                if(c.CarId == id)
                {
                    db.Cars.Remove(c);
                }
            }
            db.SaveChanges();

            List<Car> cars2 = db.Cars.ToList();
            CarListVM model = new CarListVM() { cars = cars2 };
            return View("Index", model);
        }

        [Route("voiture/modif/{*id}")]
        [Route("voiture/modif/{id?}")]
        public IActionResult EditCar(int id)
        {
            List<Car> cars = db.Cars.ToList();
            EditCarVM model = new EditCarVM();
            foreach (Car c in cars)
            {
                if (c.CarId == id)
                {
                    model = new EditCarVM() {CarId = id, ImgPath = c.ImgPath, MSRP = c.MSRP, Name = c.Name, Price = c.Price, Type = c.Type};
                }
            }


            return View("Edit",model);
        }

        public IActionResult EditCarFinal(EditCarVM car)
        {
            List<Car> cars = db.Cars.ToList();
            Car newCar = new Car() { CarId = car.CarId, Type = car.Type, Price = car.Price, Name = car.Name, MSRP = car.MSRP, ImgPath = car.ImgPath};
            foreach(Car c in cars)
            {
                if(c.CarId == car.CarId)
                {
                    db.Entry(c).CurrentValues.SetValues(newCar);
                }
            }
            db.SaveChanges();

            List<Car> cars2 = db.Cars.ToList();
            CarListVM model = new CarListVM() { cars = cars2 };
            return View("Index", model);
        }


    }
}

Views/Carlist/Edit.cshtml
@model EvoWebsite.ViewsModels.EditCarVM;
<div class="bg-form">
    <div class="container h-100 form-overlay">
        <div class="form-title">MODIFICATION D'UNE VOITURE</div>
        @using (Html.BeginForm("EditCarFinal", "Carlist", FormMethod.Post))
        {
            <div class="form-main">
                <div class="form-group">
                    <label for="name" class="form-input-title">ID</label>
                    @Html.TextBoxFor(m => m.CarId, "", new { @type = "text", @class = "form-control" })
                </div>
                <div class="form-group">
                    <label for="name" class="form-input-title">Nom</label>
                    @Html.TextBoxFor(m => m.Name, "", new { @type = "text", @class = "form-control", @required = "" })

                </div>
                <div class="form-group">
                    <label for="telephone" class="form-input-title">Image Path</label>
                    @Html.TextBoxFor(m => m.ImgPath, "", new { @type = "text", @class = "form-control", @required = "" })

                </div>
                <div class="form-group">
                    <label for="car" class="form-input-title">Prix</label>
                    @Html.TextBoxFor(m => m.Price, "", new { @type = "text", @class = "form-control", @required = "" })


                </div>
                <div class="form-group">
                    <label for="car" class="form-input-title">MSRP</label>
                    @Html.TextBoxFor(m => m.MSRP, "", new { @type = "text", @class = "form-control", @required = "" })


                </div>
                @Html.AntiForgeryToken()
                <button type="submit" class="btn btn-primary">Modifier</button>
            </div>
        }
    </div>
</div>

Views/Carlist/Index.cshtml
@model EvoWebsite.ViewsModels.CarListVM;

<div class="bg-list2">
    <div class="container h-100 list-orders-overlay">

        <div class="row">
            <div class="col-lg">

            </div>
            <div class="col-lg list-col">
                <button class="btn-card" onclick="window.location='/order/index'">Commandes</button>
                <button class="btn-card" onclick="window.location='/carlist/index'">Voitures</button>
            </div>
            <div class="col-lg">

            </div>
        </div>

        <div class="form-title">LISTE DES VOITURES</div>
        <table class="table table-striped">
            <tbody>

                <tr class="title-orders">
                    <th scope="col">#</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Prix</th>
                    <th scope="col">MSRP</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>

                @foreach (Car car in Model.cars)
                {
                    <tr class="content-orders">
                        <th scope="row">@car.CarId</th>
                        <td>@car.Name</td>
                        <td>@car.Price$</td>
                        <td>@car.MSRP$</td>
                        <td><input type="image" src="/img/btn-modif.png" class="btn-modif" onclick="window.location='/voiture/modif/@car.CarId'" /></td>
                        <td><input type="image" src="/img/btn-remove.png" class="btn-modif " onclick="remove(@car.CarId)" /></td>
                    </tr>

                }




            </tbody>
        </table>
    </div>
</div>
<script>
    function remove(id) {
        var agreed = confirm("Êtes-vous sûre de vouloir supprimer cette voiture?");
        if (agreed) {
            window.location = '/voiture/supprime/' + id;
        }
    }
</script>